name: Publish Release

on:
  workflow_dispatch:
    inputs:
      minor_increment:
        description: Minor version increment
        required: true
        default: 'false'
      major_increment:
        description: Major version increment
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          # releases are done from the main branch
          release-branch-name: "main"
          ###########################################################
          # minor version increment  e.g. 1.1.0 -> 1.2.0
          version-minor: ${{github.event.inputs.minor_increment}}
          # major version increment  e.g. 1.0.0 -> 2.0.0
          version-major: ${{github.event.inputs.major_increment}}
          # If both minor and major increment values are false, a patch
          # version increment will be performed. e.g. 1.0.0 -> 1.0.1
          ###########################################################
          # name and email of the bot in git commits
          git-release-bot-name: "xformer-bot"
          git-release-bot-email: "xformer@janeirodigital.com"
          ###########################################################
          #maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"
          maven-args: ""
          ###########################################################
          ssh-private-key: ${{ secrets.XFORMER_SSH_PRIVATE }}
          ###########################################################
          gpg-enabled: true
          gpg-key-id: ${{ secrets.XFORMER_GPG_KEY_ID }}
          gpg-key: ${{ secrets.XFORMER_GPG_KEY }}
          ###########################################################
          # configure nexus repository
          maven-repo-server-id: xformativ-nexus   # Value of the distributionManagement/repository/id field of the pom.xml
          maven-repo-server-username: ${{ secrets.XFORMATIV_MAVEN_USERNAME }}
          maven-repo-server-password: ${{ secrets.XFORMATIV_MAVEN_PASSWORD }}
